# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('C', 'CLOTHING'), ('S', 'SHOES'), ('A', 'ACCESSORIES')], default='M', max_length=1)),
                ('for_whom', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('C', 'Child')], default='M', max_length=1)),
                ('price', models.PositiveIntegerField()),
                ('picture', models.URLField(max_length=3000)),
                ('description', models.TextField()),
                ('count', models.PositiveIntegerField()),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
